-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E501']
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: flake8
        args: [--max-line-length=140]
    -   id: trailing-whitespace
    -   id: name-tests-test

-   repo: git://github.com/ivanlei/pre-commit-python-sorter
    sha: master
    hooks:
    -   id: python-import-sorter
        args: [--silent-overwrite, --force_single_line]
